name: Build Windows binaries

on:
  push:
    branches:
      - '**'

jobs:
  build-win32:
    runs-on: windows-latest
    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-binutils
    - name: Build
      shell: msys2 {0}
      run: |
        makepkg -s --noconfirm
    - uses: actions/upload-artifact@v4
      with:
        name: opencascade-lite
        path: '*.pkg.tar.zst'
